<!DOCTYPE html>
<html lang="en">
    <head>
        <title>RPC接口</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="kovey">
        <style>
            html, body{height:100%;margin:0;padding:0;}
            .refentry{position:relative;min-height:99%;overflow : hidden;}
            .container-fluid {width: 99%;padding-right: 0.25rem;padding-left: 0.25rem;margin-right: auto;margin-left: auto;}
            .refentry .refsect1 {margin-bottom: 3rem;}
            .title {position: relative;clear: both;color: #793862;}
            h3 {font-weight: 500;font-size: 1.25rem;line-height: 3rem;margin: 0 0 1.5rem;overflow: hidden;text-rendering: optimizeLegibility;}
            h3::after {display: table;width: 100%;content: " ";margin-top: -1px;border-bottom: 1px dotted;}
            .dc-description {color:#737373;}
            .refsect1 .dc-description, .refsect1 .dc-description code, .docs .sect1 .dc-description, .docs .sect1 .dc-description code {font-weight: 400;font-size: 1rem;font-family: "Fira Mono", "Source Code Pro", monospace;letter-spacing: -.0625rem;word-spacing: -.125rem;margin: 0;margin-bottom: 0px;}
            .docs .classsynopsis, .refsect1 .fieldsynopsis, .refsect1 .dc-description, .docs .sect1 .dc-description {padding: .75rem;margin-bottom: 1.5rem;}
            .docs .classsynopsis, .refsect1 .fieldsynopsis, .refsect1 .dc-description, .docs .sect1 .dc-description, div.tip, blockquote.note, div.caution, div.warning {box-shadow: inset 0 0 0 1px rgba(0,0,0,.15);border-radius: 0 0 2px 2px;}
            .docs .classsynopsis, .refsect1 .fieldsynopsis, .refsect1 .dc-description, .docs .sect1 .dc-description {background: #fff;border-color:#d9d9d9;}
            .dc-description {color: #737373;}
            strong, em {text-rendering: optimizeLegibility;}
            .methodname b, .methodname strong, .methodname a, .classsynopsis .classname, .parameter {color: #369;}
            .docs .methodname strong {font-style: normal;font-weight: normal;}
            .interfacename a, .fieldsynopsis .type, .methodsynopsis .type, .constructorsynopsis .type {color: #693;}
            footer {text-align: center;height:50px;margin-top:-55px;width:99%;bottom: 0;position:absolute;}
            .text-muted {color:#6c757d !important;}
        </style>
    </head>

    <body class="docs">
        <div class="refentry">
            <main role="main" class="container-fluid">
                <?php foreach($this->services as $service => $methods): ?>
                    <div class="refsect1 description" id="refsect1-function.substr-description">
                      <h3 class="title"><a href="/?s=<?php echo $service;?>"><?php echo $service;?></a></h3>
                        <?php if (!is_array($methods)) : ?>
                            <p><?php echo $methods; ?></p>
                        <?php else : ?>
                          <?php foreach ($methods as $name => $info): ?>
                          <div class="methodsynopsis dc-description">
                            <p class="para rdfs-comment">
                            <?php $i = 0; ?>
                            <?php foreach(explode("\n", $info['doc']) as $line): ?>
                                <?php if ($i > 0): ?>
                                    <p style="margin-top:0;margin-bottom:0;color:#000;padding-left: 0.6rem;"><?php echo $line; ?></p>
                                <?php else:  ?>
                                    <p style="margin-top:0;margin-bottom:0;color:#000;"><?php echo $line; ?></p>
                                <?php endif ?>
                                <?php $i ++; ?>
                            <?php endforeach ?>
                            </p>
                            <span class="methodname"><strong><?php echo $name; ?></strong></span>
                            ( 
                            <?php $index = 0; $total = count($info['args']);?>
                            <?php foreach ($info['args'] as $arg): ?>
                                <?php $index ++ ;?>
                                <span class="methodparam">
                                <?php if (!empty($arg['type'])): ?>
                                    <span class="type"><?php echo $arg['type']; ?></span>
                                <?php endif ?>
                                    <code class="parameter"><?php echo $arg['param'] . (strlen($arg['default']) > 0 ? (' = ' . $arg['default']) : ''); ?></code>
                                </span>
                                <?php echo $index < $total ? ', ' : ''; ?>
                            <?php endforeach ?>
                            ) <span class="type"><a href="/call?s=<?php echo $service; ?>&m=<?php echo $name;?>&a=<?php echo urlencode(json_encode($info['args'])); ?>">test</a></span>
                            </div>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>
                <?php endforeach ?>
            </main>
            <footer> 
              <p>    
                Powered by: <a href="http://www.kovey.cn/">Kovey</a> Copyright © 2018-<?php echo date('Y'); ?> Kovey.
              </p>
            </footer>
        </div>
    </body
</html>
